### PR TITLE
fix: typos in documentation files

### PR DESCRIPTION
**Pull request by leopardracer**
This pull request contains changes to improve clarity, correctness and structure.

**Description correction:**
Corrected "Documenation" to "Documentation".

Please review the changes and let me know if any additional changes are needed.

### CODE REVIEW

**Comment by stephenlacy** [comment]
Why do all your forked projects have fake bot stars?
- https://github.com/leopardracer/op-viem/stargazers
- https://github.com/leopardracer/chains/stargazers
- https://github.com/leopardracer/pessimism/stargazers

**Comment by leopardracer** [comment]
@stephenlacy Hi, these are not bots or fakes, as you claim. We are a young community, just at the beginning of our journey, and the stars come from real users who rely on on-chain activity but do not yet understand why or how to use GitHub. I asked my comrades to give me stars in order to test the functionality.

**Comment by leopardracer** [comment]
@stephenlacy Hi! Apologies for the inconvenience. I just wanted to check if there’s anything I can improve in my pull request. Please feel free to ask any questions or let me know if any changes are needed to meet the project's merge requirements. I’m happy to make adjustments!

**Comment by leopardracer** [comment]
@stephenlacy Hi! Apologies for the inconvenience. I just wanted to check if there’s anything I can improve in my pull request. Please feel free to ask any questions or let me know if any changes are needed to meet the project's merge requirements. I’m happy to make adjustments!

**Pull request closed without merging**
